### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by thejoker3000** [NinjaJc01/PensiveNotes#1]
I've followed the README.md instructions to install but the build doesn't work. I checked in the /go folder and the dependencies did download.

![image](https://user-images.githubusercontent.com/53082621/118396810-84b51c00-b651-11eb-9837-f1c99d5c4aa9.png)

**Comment by NinjaJc01** [comment]
You should not be installing this yourself.
It's explicitly designed to be vulnerable.
Please use the copy hosted on tryhackme.
